// ══════════════════════════════════════════════════════════════
// 文献ダミーデータ（50件以上）
// PubMed API導入後は searchPapers() を差し替えるだけで動作する
// ══════════════════════════════════════════════════════════════

export type EvidenceLevel = "A" | "B" | "C" | "D";

export interface Paper {
  id:            string;
  title:         string;
  titleJa:       string;
  authors:       string;
  journal:       string;
  year:          number;
  evidenceLevel: EvidenceLevel;
  url:           string;
  summary:       string;
  keywords:      string[];
  isOpenAccess:  boolean;
}

export const DUMMY_PAPERS: Paper[] = [
  // ── 変形性膝関節症 ──────────────────────────────────────────
  {
    id: "p1",
    title: "Exercise therapy for knee osteoarthritis: a systematic review and meta-analysis",
    titleJa: "変形性膝関節症に対する運動療法：システマティックレビューとメタ解析",
    authors: "Tanaka K, Yamamoto T, et al.",
    journal: "Physical Therapy", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "変形性膝関節症患者2,156例を対象とした24件のRCT統合解析。運動療法はVASスコアを平均2.4点改善し、WOMAC機能スコアを有意に向上させた。低負荷高反復の大腿四頭筋強化との組み合わせが最も効果的であった。",
    keywords: ["膝", "変形性膝関節症", "knee", "osteoarthritis", "OA", "運動療法", "RCT", "WOMAC", "大腿四頭筋"],
    isOpenAccess: true,
  },
  {
    id: "p2",
    title: "Aquatic exercise versus land-based exercise for knee osteoarthritis: an RCT",
    titleJa: "変形性膝関節症における水中運動対陸上運動：RCT",
    authors: "Suzuki M, Kato H, et al.",
    journal: "Journal of Rheumatology", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "変形性膝関節症患者96例を対象とした水中運動と陸上運動の比較RCT。水中運動群はNRSを平均1.9点改善し、疼痛への負担が少ない点で優れた。機能スコアは両群で同等の改善が得られた。",
    keywords: ["膝", "水中", "変形性膝関節症", "aquatic", "knee", "osteoarthritis", "水中療法"],
    isOpenAccess: false,
  },
  {
    id: "p3",
    title: "Effects of quadriceps strengthening on knee pain and function: systematic review",
    titleJa: "大腿四頭筋強化が膝疼痛と機能に与える影響：系統的レビュー",
    authors: "Nakamura R, Ito S, et al.",
    journal: "Annals of Physical and Rehabilitation Medicine", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "大腿四頭筋強化訓練の膝疼痛・機能への効果を検討した17件のRCT系統的レビュー。等速・等尺・等張運動すべてで疼痛軽減効果を確認。特に術後早期の等尺性収縮訓練の即効性が示された。",
    keywords: ["大腿四頭筋", "膝", "knee", "筋力強化", "疼痛", "RCT"],
    isOpenAccess: true,
  },
  // ── 脳卒中 ─────────────────────────────────────────────────
  {
    id: "p4",
    title: "Task-oriented training versus traditional physiotherapy for stroke: upper limb function",
    titleJa: "脳卒中患者における課題指向型訓練対従来理学療法：上肢機能への効果",
    authors: "Nakamura H, Watanabe Y, et al.",
    journal: "Neurorehabilitation and Neural Repair", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "脳卒中後上肢機能障害患者120例を対象としたRCT。課題指向型訓練はFMA上肢スコアを平均4.8点改善。BI改善度も高く、退院後3カ月時点での効果持続を確認した。",
    keywords: ["脳卒中", "stroke", "片麻痺", "上肢", "課題指向型", "FMA", "BI", "脳梗塞"],
    isOpenAccess: true,
  },
  {
    id: "p5",
    title: "Robot-assisted therapy for upper limb rehabilitation after stroke: meta-analysis",
    titleJa: "脳卒中後上肢リハビリテーションにおけるロボット支援療法：メタ解析",
    authors: "Yamada K, Sato N, et al.",
    journal: "Journal of NeuroEngineering and Rehabilitation", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "脳卒中後上肢リハビリに対するロボット療法の効果を検討した28件のRCTメタ解析。通常療法と比較してFMA-UEを平均2.9点有意に改善。訓練強度の増加が功を奏していると考えられた。",
    keywords: ["脳卒中", "stroke", "ロボット", "robot", "上肢", "リハビリ", "片麻痺"],
    isOpenAccess: true,
  },
  {
    id: "p6",
    title: "Constraint-induced movement therapy for chronic stroke: a systematic review",
    titleJa: "慢性期脳卒中に対する強制使用運動療法：系統的レビュー",
    authors: "Kobayashi T, Endo K, et al.",
    journal: "Stroke", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "強制使用運動療法（CI療法）の慢性期脳卒中患者への効果を検討した21件のRCT系統的レビュー。上肢機能・日常生活への使用頻度ともに有意改善。慢性期でも可塑性変化が起こることが示された。",
    keywords: ["脳卒中", "stroke", "CI療法", "上肢", "慢性期", "片麻痺", "constraint"],
    isOpenAccess: false,
  },
  {
    id: "p7",
    title: "Early mobilization after ischemic stroke: a randomized controlled trial",
    titleJa: "虚血性脳卒中後の早期離床：無作為化比較試験",
    authors: "Fujita M, Ueda T, et al.",
    journal: "The Lancet", year: 2023, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "虚血性脳卒中患者220例での超早期離床（24時間以内）対標準離床の比較RCT。超早期群は3カ月後mRSが有意に改善。死亡率・合併症率に有意差なく安全性も確認された。",
    keywords: ["脳卒中", "stroke", "離床", "早期", "脳梗塞", "mRS", "mobilization"],
    isOpenAccess: false,
  },
  {
    id: "p8",
    title: "Gait rehabilitation using body-weight support treadmill after stroke: RCT",
    titleJa: "脳卒中後の体重支持トレッドミル歩行訓練：RCT",
    authors: "Ishida Y, Kondo M, et al.",
    journal: "Neurorehabilitation and Neural Repair", year: 2020, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "脳卒中後歩行障害患者80例を対象とした体重支持トレッドミル訓練のRCT。訓練群は10m歩行速度が平均0.18m/s向上。FIMの歩行項目も有意に改善し、地域在住復帰率も高かった。",
    keywords: ["脳卒中", "stroke", "歩行", "トレッドミル", "treadmill", "免荷", "BWS"],
    isOpenAccess: true,
  },
  // ── 腰痛 ───────────────────────────────────────────────────
  {
    id: "p9",
    title: "Manual therapy combined with exercise for chronic low back pain: RCT",
    titleJa: "慢性腰痛に対する徒手療法と運動療法の併用：RCT",
    authors: "Honda K, Matsumoto S, et al.",
    journal: "Journal of Orthopaedic & Sports Physical Therapy", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "慢性腰痛患者86例のRCT。徒手療法＋運動療法は運動療法単独よりNRSを1.8点有意に改善。ODI・腰椎ROM・12週後の効果持続も確認された。",
    keywords: ["腰痛", "腰部", "低背痛", "manual therapy", "徒手療法", "NRS", "ODI", "chronic"],
    isOpenAccess: false,
  },
  {
    id: "p10",
    title: "Core stabilization exercise for nonspecific low back pain: systematic review",
    titleJa: "非特異的腰痛に対するコアスタビリティ運動：系統的レビュー",
    authors: "Watanabe A, Saito K, et al.",
    journal: "Physical Therapy", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "非特異的腰痛患者に対するコアスタビリティ運動の効果を検討した22件のRCT系統的レビュー。短期〜中期的な疼痛軽減および機能改善に優れた効果。長期的効果は一般運動療法と同等だった。",
    keywords: ["腰痛", "コア", "core", "体幹安定化", "stabilization", "non-specific"],
    isOpenAccess: true,
  },
  {
    id: "p11",
    title: "Lumbar spinal stenosis rehabilitation: a randomized controlled trial",
    titleJa: "腰部脊柱管狭窄症のリハビリテーション：RCT",
    authors: "Miyamoto T, Goto H, et al.",
    journal: "Spine", year: 2023, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "腰部脊柱管狭窄症患者60例を対象としたRCT。体幹筋強化・神経モビライゼーション・歩行訓練を組み合わせたプログラムが間欠性跛行距離を平均48%改善。VAS・ODIも有意低下した。",
    keywords: ["腰部脊柱管狭窄症", "狭窄", "間欠性跛行", "腰痛", "lumbar", "stenosis"],
    isOpenAccess: false,
  },
  {
    id: "p12",
    title: "McKenzie method versus other therapies for mechanical low back pain",
    titleJa: "機械的腰痛に対するマッケンジー法対他療法の比較",
    authors: "Inoue T, Suzuki R, et al.",
    journal: "Spine", year: 2020, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "機械的腰痛患者に対するマッケンジー法の効果を検討した15件のRCTメタ解析。短期的疼痛軽減（SMD=-0.58）に優れ、特に方向選択性を持つ患者での高い効果が示された。",
    keywords: ["腰痛", "マッケンジー", "McKenzie", "mechanical", "方向選択", "lower back"],
    isOpenAccess: true,
  },
  // ── 肩関節 ─────────────────────────────────────────────────
  {
    id: "p13",
    title: "Shoulder rehabilitation after rotator cuff repair: early vs delayed mobilization",
    titleJa: "腱板修復後のリハビリテーション：早期対遅延可動化の比較",
    authors: "Hayashi T, Nishimura K, et al.",
    journal: "American Journal of Sports Medicine", year: 2020, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "腱板修復後プロトコル比較コホート研究（n=142）。早期可動化群はROM回復が3週間早く、最終DASH値に有意差なし。再断裂リスクも両群で差がなかった。",
    keywords: ["肩", "腱板", "rotator cuff", "shoulder", "ROM", "術後リハ", "可動化"],
    isOpenAccess: false,
  },
  {
    id: "p14",
    title: "Physical therapy for shoulder impingement syndrome: systematic review",
    titleJa: "肩インピンジメント症候群に対する理学療法：系統的レビュー",
    authors: "Kawamura S, Abe T, et al.",
    journal: "British Journal of Sports Medicine", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "肩インピンジメント症候群に対する理学療法の効果を検討した19件のRCT系統的レビュー。肩甲骨安定化・インナーマッスル強化・関節モビライゼーションの組み合わせが最も効果的であった。",
    keywords: ["肩", "インピンジメント", "impingement", "肩甲骨", "rotator", "shoulder"],
    isOpenAccess: true,
  },
  {
    id: "p15",
    title: "Baseball shoulder injuries and pitching biomechanics: a systematic review",
    titleJa: "野球肩障害と投球バイオメカニクス：系統的レビュー",
    authors: "Taniguchi R, Kuno S, et al.",
    journal: "Journal of Shoulder and Elbow Surgery", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "野球投手の肩障害に関する23件の研究の系統的レビュー。投球フォームの欠点（体幹回旋不足・肩甲骨機能不全）が障害リスクを高める。理学療法での体幹・肩甲骨トレーニングの有効性を確認した。",
    keywords: ["肩", "野球", "baseball", "野球肩", "投球障害", "投球フォーム", "インピンジメント", "pitcher", "rotator cuff baseball"],
    isOpenAccess: true,
  },
  {
    id: "p16",
    title: "Frozen shoulder: manipulation under anesthesia versus physical therapy",
    titleJa: "凍結肩：麻酔下授動術対理学療法の比較",
    authors: "Mori T, Okada K, et al.",
    journal: "Journal of Bone and Joint Surgery", year: 2021, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "凍結肩患者100例を対象とした麻酔下授動術と理学療法の比較RCT。1年後のROM・VAS・DASH値は両群で同等の改善。理学療法群は合併症が少なく費用効果に優れていた。",
    keywords: ["凍結肩", "五十肩", "frozen shoulder", "肩関節", "ROM", "授動術"],
    isOpenAccess: false,
  },
  // ── 股関節 ─────────────────────────────────────────────────
  {
    id: "p17",
    title: "Aquatic therapy for hip osteoarthritis: systematic review",
    titleJa: "股関節変形性関節症に対する水中療法：系統的レビュー",
    authors: "Fukuda A, Mori H, et al.",
    journal: "Clinical Rehabilitation", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "股関節変形性関節症への水中療法を検討した8件のRCT系統的レビュー。陸上訓練と比較して疼痛・機能改善に同等の効果。体重負荷への忍容性が低い患者への第一選択として推奨された。",
    keywords: ["股関節", "THA", "変形性", "水中", "aquatic", "hip", "osteoarthritis"],
    isOpenAccess: false,
  },
  {
    id: "p18",
    title: "Rehabilitation after total hip arthroplasty: early vs late discharge protocols",
    titleJa: "人工股関節全置換術後のリハビリテーション：早期対後期退院プロトコルの比較",
    authors: "Takahashi N, Kamijo M, et al.",
    journal: "Orthopaedics & Traumatology", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "THA後の早期退院プロトコル（4日以内）対従来プロトコルの比較RCT（n=112）。早期退院群は30日後Harris Hip Scoreで同等の結果。合併症率・再入院率に有意差なし。",
    keywords: ["THA", "股関節", "人工関節", "hip arthroplasty", "術後リハ", "退院"],
    isOpenAccess: true,
  },
  // ── 呼吸器・COPD ───────────────────────────────────────────
  {
    id: "p19",
    title: "Pulmonary rehabilitation in COPD: systematic review of exercise capacity and QOL",
    titleJa: "COPDにおける肺リハビリテーション：運動耐容能と生活の質への効果",
    authors: "Sato R, Kobayashi N, et al.",
    journal: "Respirology", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "COPD患者への肺リハビリテーション効果を検討した29件のRCTメタ解析。6MWTを平均43m改善し、SGRQ総スコアを7.1点低下。呼吸筋トレーニングとの組み合わせで効果が増強された。",
    keywords: ["COPD", "肺", "呼吸", "肺リハ", "respiratory", "6MWT", "SGRQ", "pulmonary"],
    isOpenAccess: true,
  },
  {
    id: "p20",
    title: "High-intensity interval training versus moderate exercise in COPD: RCT",
    titleJa: "COPDにおける高強度インターバルトレーニング対中等度運動：RCT",
    authors: "Wada K, Endo M, et al.",
    journal: "European Respiratory Journal", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "COPD患者64例での高強度インターバル訓練と中等度継続運動の比較RCT。HIIT群は6MWT・VO2peak・BODE指数において中等度継続群より有意に優れた結果を示した。",
    keywords: ["COPD", "HIIT", "高強度", "呼吸リハ", "肺", "6MWT"],
    isOpenAccess: false,
  },
  {
    id: "p21",
    title: "Inspiratory muscle training in patients with COPD: meta-analysis",
    titleJa: "COPD患者における呼吸筋トレーニング：メタ解析",
    authors: "Yamamoto C, Hirano T, et al.",
    journal: "Chest", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "COPD患者への吸気筋トレーニング（IMT）効果を検討した18件のRCTメタ解析。PImax・6MWT・dyspnea scoreを有意に改善。週5回以上・30分以上の訓練頻度が特に有効であった。",
    keywords: ["COPD", "呼吸筋", "吸気筋", "IMT", "respiratory muscle", "PImax"],
    isOpenAccess: true,
  },
  // ── 転倒予防・バランス ─────────────────────────────────────
  {
    id: "p22",
    title: "Balance training for fall prevention in older adults: updated meta-analysis",
    titleJa: "高齢者の転倒予防におけるバランス訓練：最新メタ解析",
    authors: "Yoshida M, Kato T, et al.",
    journal: "Journal of Geriatric Physical Therapy", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "地域在住高齢者へのバランス訓練効果を検討した19件のRCTメタ解析。週3回以上の継続訓練は転倒発生率を33%低下。BBS・TUGスコアに有意改善が認められた。",
    keywords: ["高齢者", "転倒", "バランス", "BBS", "TUG", "fall prevention", "elderly"],
    isOpenAccess: false,
  },
  {
    id: "p23",
    title: "Tai chi for fall prevention in community-dwelling older adults: RCT",
    titleJa: "地域在住高齢者の転倒予防における太極拳：RCT",
    authors: "Noda Y, Hara M, et al.",
    journal: "New England Journal of Medicine", year: 2023, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "転倒リスクのある地域在住高齢者200例を対象とした太極拳のRCT。週2回24週間の太極拳訓練は転倒リスクを31%低下。バランス機能・下肢筋力・恐怖感の改善も認められた。",
    keywords: ["高齢者", "転倒", "太極拳", "tai chi", "バランス", "fall", "地域在住"],
    isOpenAccess: true,
  },
  {
    id: "p24",
    title: "Exercise interventions for preventing falls in nursing homes: systematic review",
    titleJa: "介護施設入居高齢者の転倒予防運動介入：系統的レビュー",
    authors: "Tanaka M, Goto A, et al.",
    journal: "Cochrane Database of Systematic Reviews", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "介護施設入居高齢者への転倒予防運動介入を検討した14件のRCT系統的レビュー。複合運動プログラム（筋力＋バランス＋歩行）が最も効果的で転倒率を25%低下させた。",
    keywords: ["高齢者", "介護施設", "転倒", "fall", "nursing home", "バランス"],
    isOpenAccess: true,
  },
  // ── パーキンソン病 ─────────────────────────────────────────
  {
    id: "p25",
    title: "Gait training with body weight support for Parkinson's disease: QOL outcomes",
    titleJa: "パーキンソン病に対する免荷式歩行訓練：QOLアウトカム",
    authors: "Imai Y, Sasaki H, et al.",
    journal: "Parkinsonism & Related Disorders", year: 2023, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "パーキンソン病患者54例への免荷式トレッドミル訓練効果の検討。6週間で歩行速度が0.12m/s改善。歩幅延長・凍結歩行頻度低下・PDQ-39QOL指標の有意改善を確認した。",
    keywords: ["パーキンソン", "Parkinson", "歩行", "トレッドミル", "treadmill", "免荷", "凍結歩行"],
    isOpenAccess: true,
  },
  {
    id: "p26",
    title: "Rhythmic auditory stimulation for gait in Parkinson's disease: meta-analysis",
    titleJa: "パーキンソン病の歩行に対するリズム聴覚刺激：メタ解析",
    authors: "Shimizu E, Ueno M, et al.",
    journal: "Journal of Neurological Sciences", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "パーキンソン病患者への聴覚リズム刺激（RAS）の歩行効果を検討した12件のRCTメタ解析。歩行速度・歩幅・ケイデンスを有意に改善。凍結歩行・転倒リスクの低下も示された。",
    keywords: ["パーキンソン", "Parkinson", "聴覚刺激", "RAS", "歩行", "リズム", "cueing"],
    isOpenAccess: true,
  },
  // ── 大腿骨近位部骨折 ─────────────────────────────────────
  {
    id: "p27",
    title: "Early mobilization after hip fracture surgery: systematic review",
    titleJa: "大腿骨近位部骨折術後の早期離床：系統的レビュー",
    authors: "Uchida K, Nishio T, et al.",
    journal: "Archives of Physical Medicine and Rehabilitation", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "大腿骨近位部骨折術後早期離床の効果を検討した16件のRCT系統的レビュー。術後24時間以内の離床は合併症発生率・入院期間・退院先に有意に影響。1年後ADL・死亡率にも関連した。",
    keywords: ["大腿骨近位部骨折", "股関節骨折", "hip fracture", "術後", "離床", "骨折"],
    isOpenAccess: true,
  },
  {
    id: "p28",
    title: "Progressive resistance training after hip fracture: RCT",
    titleJa: "大腿骨近位部骨折後の漸進的抵抗運動：RCT",
    authors: "Kimura H, Tanaka R, et al.",
    journal: "Journal of the American Geriatrics Society", year: 2021, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "大腿骨近位部骨折後患者80例への漸進的抵抗訓練RCT。介入群は6カ月後の下肢筋力・歩行速度・転倒リスクが有意に改善。地域在住復帰率も介入群で14%高かった。",
    keywords: ["大腿骨近位部骨折", "hip fracture", "筋力強化", "高齢者", "骨折"],
    isOpenAccess: false,
  },
  // ── 変形性股関節症 ─────────────────────────────────────────
  {
    id: "p29",
    title: "Exercise therapy for hip osteoarthritis: Cochrane systematic review",
    titleJa: "変形性股関節症に対する運動療法：コクランシステマティックレビュー",
    authors: "Aoki S, Nakano H, et al.",
    journal: "Cochrane Database of Systematic Reviews", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "変形性股関節症患者への運動療法効果を検討した22件のRCT系統的レビュー。疼痛・機能・QOL全てで有意改善。水中・陸上の差は小さく、患者の好みに応じた選択が推奨された。",
    keywords: ["股関節", "変形性股関節症", "hip", "osteoarthritis", "運動療法"],
    isOpenAccess: true,
  },
  // ── 脊髄損傷 ──────────────────────────────────────────────
  {
    id: "p30",
    title: "Locomotor training for incomplete spinal cord injury: systematic review",
    titleJa: "不全脊髄損傷に対する歩行訓練：系統的レビュー",
    authors: "Sakai T, Hori N, et al.",
    journal: "Spinal Cord", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "不全脊髄損傷患者への歩行訓練効果を検討した15件のRCT系統的レビュー。体重支持トレッドミルと地上歩行訓練の組み合わせが歩行機能・速度・持久性を最も改善した。",
    keywords: ["脊髄損傷", "spinal cord injury", "SCI", "歩行", "不全麻痺", "locomotor"],
    isOpenAccess: false,
  },
  // ── 心臓リハ ──────────────────────────────────────────────
  {
    id: "p31",
    title: "Cardiac rehabilitation after myocardial infarction: meta-analysis",
    titleJa: "心筋梗塞後の心臓リハビリテーション：メタ解析",
    authors: "Ito K, Yamashita R, et al.",
    journal: "Journal of the American College of Cardiology", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "心筋梗塞後の心臓リハビリ効果を検討した45件のRCTメタ解析。心臓死亡率を20%低下・再入院率を18%低下。有酸素運動・筋力訓練・患者教育の包括的プログラムが有効であった。",
    keywords: ["心臓リハ", "cardiac rehab", "心筋梗塞", "心不全", "循環器", "有酸素"],
    isOpenAccess: true,
  },
  {
    id: "p32",
    title: "Exercise training in heart failure: systematic review",
    titleJa: "心不全患者における運動療法：系統的レビュー",
    authors: "Endo K, Tanimura S, et al.",
    journal: "European Heart Journal", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "心不全患者への運動訓練効果を検討した33件のRCT系統的レビュー。最大酸素摂取量・QOL・入院日数を有意に改善。中等度有酸素運動の安全性も確認された。",
    keywords: ["心不全", "heart failure", "運動療法", "cardiac", "VO2max", "QOL"],
    isOpenAccess: true,
  },
  // ── 膝関節TKA後 ──────────────────────────────────────────
  {
    id: "p33",
    title: "Preoperative exercise for TKA outcomes: systematic review",
    titleJa: "人工膝関節全置換術の術前運動が術後アウトカムに与える影響：系統的レビュー",
    authors: "Ogata K, Nakata M, et al.",
    journal: "Knee Surgery, Sports Traumatology, Arthroscopy", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "TKA前の術前運動療法が術後アウトカムに与える影響を検討した11件のRCT系統的レビュー。術前運動群は術後早期の疼痛・筋力・機能で有意に優れた成績を示した。",
    keywords: ["TKA", "人工膝関節", "knee arthroplasty", "術前リハ", "膝", "術後"],
    isOpenAccess: false,
  },
  // ── 肘・前腕 ──────────────────────────────────────────────
  {
    id: "p34",
    title: "Physical therapy for lateral elbow tendinopathy: RCT",
    titleJa: "外側上顆炎に対する理学療法：RCT",
    authors: "Hashimoto K, Goto Y, et al.",
    journal: "British Journal of Sports Medicine", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "外側上顆炎患者72例のRCT。エキセントリック訓練＋徒手療法は疼痛自由肢位伸展・握力・VASを有意に改善。12週後の寛解率が対照群より22%高かった。",
    keywords: ["肘", "テニス肘", "外側上顆炎", "lateral epicondylitis", "elbow", "エキセントリック"],
    isOpenAccess: true,
  },
  // ── 足関節 ─────────────────────────────────────────────────
  {
    id: "p35",
    title: "Proprioceptive training for ankle instability: meta-analysis",
    titleJa: "足関節不安定性に対する固有受容感覚訓練：メタ解析",
    authors: "Kato S, Iwata H, et al.",
    journal: "Journal of Athletic Training", year: 2021, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "慢性足関節不安定性患者への固有受容感覚訓練効果の14件のRCTメタ解析。バランス・再損傷予防・患者報告アウトカムを有意に改善。週3〜5回・6〜12週間のプログラムが最適だった。",
    keywords: ["足関節", "足首", "ankle", "不安定性", "固有受容感覚", "proprioception", "捻挫"],
    isOpenAccess: true,
  },
  // ── 頸椎 ──────────────────────────────────────────────────
  {
    id: "p36",
    title: "Manual therapy and exercise for neck pain: Cochrane review",
    titleJa: "頸部疼痛に対する徒手療法と運動療法：コクランレビュー",
    authors: "Fujiwara T, Okamoto K, et al.",
    journal: "Cochrane Database of Systematic Reviews", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "頸部疼痛患者への徒手療法・運動療法の効果を検討した24件のRCT系統的レビュー。両者の組み合わせが疼痛・機能・QOLで最も優れた短中期効果を示した。",
    keywords: ["頸椎", "頸部痛", "neck pain", "cervical", "徒手療法", "頸肩"],
    isOpenAccess: true,
  },
  // ── 廃用症候群 ────────────────────────────────────────────
  {
    id: "p37",
    title: "Early mobilization to prevent deconditioning in ICU patients: RCT",
    titleJa: "ICU患者の廃用予防のための早期離床：RCT",
    authors: "Nishida T, Arai M, et al.",
    journal: "Critical Care Medicine", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "ICU患者での早期理学療法の廃用予防効果のRCT（n=104）。ICU入室48時間以内の理学療法開始群は退院時FIM・筋力・QOLが有意に優れた。人工呼吸器装着中でも安全に実施可能であった。",
    keywords: ["廃用症候群", "ICU", "早期離床", "廃用", "deconditioning", "重症患者"],
    isOpenAccess: false,
  },
  // ── スポーツ外傷 ──────────────────────────────────────────
  {
    id: "p38",
    title: "ACL reconstruction rehabilitation: return-to-sport criteria systematic review",
    titleJa: "ACL再建術後リハビリテーション：スポーツ復帰基準の系統的レビュー",
    authors: "Yamada T, Ishii S, et al.",
    journal: "British Journal of Sports Medicine", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "ACL再建術後スポーツ復帰基準を検討した32件の研究の系統的レビュー。筋力比（85%以上）＋機能テスト＋心理的準備の複合基準充足で再断裂リスクが大幅低下した。",
    keywords: ["ACL", "前十字靭帯", "スポーツ復帰", "膝", "術後リハ", "knee", "ligament"],
    isOpenAccess: true,
  },
  {
    id: "p39",
    title: "Hamstring injuries in athletes: prevention and rehabilitation",
    titleJa: "アスリートのハムストリング損傷：予防とリハビリテーション",
    authors: "Sugawara K, Inoue H, et al.",
    journal: "Sports Medicine", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "アスリートのハムストリング損傷予防・リハに関する29件の研究の系統的レビュー。ノルディックハムストリングカール訓練が損傷率を51%低下。エキセントリック重視の段階的リハが再発防止に有効だった。",
    keywords: ["ハムストリング", "スポーツ", "肉離れ", "hamstring", "アスリート", "予防"],
    isOpenAccess: true,
  },
  // ── 糖尿病・代謝 ─────────────────────────────────────────
  {
    id: "p40",
    title: "Exercise for type 2 diabetes mellitus: systematic review",
    titleJa: "2型糖尿病に対する運動療法：系統的レビュー",
    authors: "Hayashi N, Matsuda K, et al.",
    journal: "Diabetes Care", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "2型糖尿病患者への運動療法効果を検討した51件のRCTメタ解析。有酸素＋レジスタンス組み合わせがHbA1cを最大1.2%低下。血糖コントロール・体重・脂質プロファイルを包括的に改善した。",
    keywords: ["糖尿病", "diabetes", "運動療法", "HbA1c", "代謝", "血糖"],
    isOpenAccess: true,
  },
  // ── リハ全般 ──────────────────────────────────────────────
  {
    id: "p41",
    title: "Telerehabilitation effectiveness: systematic review and meta-analysis",
    titleJa: "遠隔リハビリテーションの有効性：系統的レビューとメタ解析",
    authors: "Ozawa T, Yamashiro K, et al.",
    journal: "Journal of Medical Internet Research", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "遠隔リハビリテーションの有効性を検討した38件のRCT系統的レビュー。対面リハと比較して機能・QOL・患者満足度で同等の効果を示した。通院困難患者への有望な代替手段として評価された。",
    keywords: ["遠隔リハ", "telerehabilitation", "在宅", "遠隔", "デジタル"],
    isOpenAccess: true,
  },
  {
    id: "p42",
    title: "Patient education in physical therapy: impact on outcomes",
    titleJa: "理学療法における患者教育：アウトカムへの影響",
    authors: "Hino A, Kawasaki T, et al.",
    journal: "Physical Therapy", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "理学療法における患者教育の効果を検討した20件のRCT系統的レビュー。Pain neuroscience education（PNE）は慢性疼痛患者の疼痛catastrophizing・機能・QOLを有意に改善した。",
    keywords: ["患者教育", "PNE", "疼痛教育", "慢性疼痛", "心理社会的"],
    isOpenAccess: true,
  },
  // ── 小児 ──────────────────────────────────────────────────
  {
    id: "p43",
    title: "Constraint-induced therapy for pediatric hemiplegic cerebral palsy: RCT",
    titleJa: "小児片麻痺性脳性麻痺に対する強制使用療法：RCT",
    authors: "Muto A, Chiba Y, et al.",
    journal: "Developmental Medicine and Child Neurology", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "片麻痺性脳性麻痺小児45例を対象としたCI療法RCT。3週間の集中訓練で患側上肢の使用頻度・機能が有意改善。効果は12カ月後も維持された。",
    keywords: ["脳性麻痺", "cerebral palsy", "小児", "片麻痺", "CI療法", "pediatrics"],
    isOpenAccess: false,
  },
  {
    id: "p44",
    title: "Physical therapy for developmental coordination disorder in children",
    titleJa: "小児の発達性協調運動障害に対する理学療法",
    authors: "Fukushima H, Ogura T, et al.",
    journal: "Research in Developmental Disabilities", year: 2021, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "発達性協調運動障害（DCD）小児への理学療法効果を検討した12件のRCT系統的レビュー。課題指向型訓練・感覚統合療法・認知アプローチが運動スキル向上に有効と示された。",
    keywords: ["小児", "発達", "DCD", "協調運動", "児童", "pediatrics"],
    isOpenAccess: true,
  },
  // ── がんリハ ──────────────────────────────────────────────
  {
    id: "p45",
    title: "Exercise in cancer survivors: systematic review of effects on fatigue and QOL",
    titleJa: "がんサバイバーにおける運動療法：倦怠感とQOLへの効果の系統的レビュー",
    authors: "Aoyama S, Mori N, et al.",
    journal: "Journal of Clinical Oncology", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "がんサバイバーへの運動療法効果を検討した62件のRCTメタ解析。がん関連倦怠感・うつ・QOLを有意改善。有酸素＋レジスタンス組み合わせが最も効果的で安全性も確認された。",
    keywords: ["がん", "cancer", "サバイバー", "倦怠感", "QOL", "oncology", "腫瘍"],
    isOpenAccess: true,
  },
  // ── 認知症 ────────────────────────────────────────────────
  {
    id: "p46",
    title: "Physical exercise for cognitive function in older adults with dementia: RCT",
    titleJa: "認知症高齢者の認知機能に対する身体運動：RCT",
    authors: "Watanabe M, Ota H, et al.",
    journal: "JAMA", year: 2022, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "軽度認知機能障害・認知症高齢者180例への有酸素運動RCT。週3回24週間の有酸素運動は対照群と比較してMMSE・CDR・ADLスコアの低下を有意に緩徐にした。",
    keywords: ["認知症", "dementia", "認知機能", "高齢者", "有酸素", "MCI"],
    isOpenAccess: true,
  },
  // ── 骨粗鬆症 ─────────────────────────────────────────────
  {
    id: "p47",
    title: "Exercise for osteoporosis prevention and treatment: meta-analysis",
    titleJa: "骨粗鬆症予防・治療のための運動：メタ解析",
    authors: "Kato E, Oshiro A, et al.",
    journal: "Osteoporosis International", year: 2023, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "骨粗鬆症への運動療法効果を検討した39件のRCTメタ解析。インパクトエクササイズ＋レジスタンストレーニングが腰椎・大腿骨近位部BMDを有意増加させた。転倒予防効果も確認された。",
    keywords: ["骨粗鬆症", "osteoporosis", "骨密度", "BMD", "転倒", "骨折予防"],
    isOpenAccess: true,
  },
  // ── 投球・スポーツ特化 ────────────────────────────────────
  {
    id: "p48",
    title: "Shoulder rotator cuff strengthening in baseball pitchers: prevention study",
    titleJa: "野球投手における肩腱板強化訓練：予防研究",
    authors: "Koike S, Muto Y, et al.",
    journal: "American Journal of Sports Medicine", year: 2023, evidenceLevel: "B",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "高校野球投手230名を対象とした腱板強化予防プログラムの前向きコホート研究。肩内・外旋筋強化プログラム実施群は肩障害発生率が対照群より42%低く、投球パフォーマンスも向上した。",
    keywords: ["野球", "投球障害", "投球フォーム", "野球肩", "肩", "baseball shoulder", "rotator cuff baseball", "pitcher", "pitching injury", "shoulder impingement"],
    isOpenAccess: false,
  },
  {
    id: "p49",
    title: "Scapular dyskinesis and shoulder pain in throwing athletes: systematic review",
    titleJa: "投球アスリートの肩甲骨機能不全と肩疼痛：系統的レビュー",
    authors: "Hashimoto Y, Eto T, et al.",
    journal: "Journal of Shoulder and Elbow Surgery", year: 2022, evidenceLevel: "A",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "投球系アスリートの肩甲骨機能不全と肩疼痛の関連を検討した18件の研究系統的レビュー。肩甲骨機能不全は肩疼痛・障害リスクと有意に関連。肩甲骨安定化訓練による疼痛改善効果も確認された。",
    keywords: ["肩甲骨", "投球", "野球", "baseball shoulder", "scapula", "dyskinesis", "野球肩", "pitching injury"],
    isOpenAccess: true,
  },
  {
    id: "p50",
    title: "Hip flexor tightness and lower back pain in soccer players: cohort study",
    titleJa: "サッカー選手の腸腰筋タイトネスと腰痛：コホート研究",
    authors: "Nagano T, Oda K, et al.",
    journal: "Sports Health", year: 2021, evidenceLevel: "C",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "プロサッカー選手120名のコホート研究。腸腰筋タイトネス・体幹安定性低下が腰痛リスクと有意に関連。ストレッチングと体幹強化を組み合わせた予防プログラムが腰痛発生率を34%低下した。",
    keywords: ["腸腰筋", "腰痛", "サッカー", "スポーツ", "体幹", "lower back"],
    isOpenAccess: false,
  },
  {
    id: "p51",
    title: "Knee valgus during landing in female athletes: ACL injury risk",
    titleJa: "女性アスリートの着地時膝外反：ACL損傷リスク",
    authors: "Saito A, Kondo T, et al.",
    journal: "American Journal of Sports Medicine", year: 2023, evidenceLevel: "C",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "女性アスリート150名のコホート研究。着地時の膝外反角度はACL損傷リスクと有意に相関（HR=2.8）。股関節外転筋・体幹トレーニングによる膝外反矯正プログラムの予防効果が示された。",
    keywords: ["ACL", "膝", "knee", "女性", "スポーツ", "着地", "外反", "valgus"],
    isOpenAccess: true,
  },
  {
    id: "p52",
    title: "Return to sport criteria after ACL reconstruction: reliability and validity",
    titleJa: "ACL再建後のスポーツ復帰基準：信頼性と妥当性の検討",
    authors: "Ishikawa T, Maeda N, et al.",
    journal: "KSSTA", year: 2022, evidenceLevel: "C",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    summary: "ACL再建後スポーツ復帰基準の信頼性・妥当性を検討した前向き研究。筋力指数85%以上＋ホップテスト合格＋IKDC評価が再断裂リスク低減に有効。心理的準備状態の評価追加が推奨された。",
    keywords: ["ACL", "スポーツ復帰", "膝", "術後", "復帰基準", "return to sport"],
    isOpenAccess: false,
  },
];

// ══════════════════════════════════════════════════════════════
// 参考書ダミーデータ（カテゴリ別 10冊以上）
// ══════════════════════════════════════════════════════════════

export interface Book {
  id:        string;
  title:     string;
  authors:   string;
  publisher: string;
  year:      number;
  price:     string;
  coverUrl:  string;
  summary:   string;
  keywords:  string[];
  category:  string;
}

export const BOOK_CATEGORIES = [
  { id: "neuro",    label: "脳卒中・神経" },
  { id: "ortho",    label: "運動器・整形外科" },
  { id: "internal", label: "内部障害・循環器" },
  { id: "resp",     label: "呼吸器" },
  { id: "peds",     label: "小児リハ" },
  { id: "eval",     label: "評価・測定" },
  { id: "anatomy",  label: "解剖学・生理学" },
  { id: "exam",     label: "国家試験対策" },
] as const;

export type BookCategoryId = typeof BOOK_CATEGORIES[number]["id"];

export const DUMMY_BOOKS: Book[] = [
  // ── 脳卒中・神経（10冊）────────────────────────────────────
  { id: "b1",  category: "neuro",    title: "脳卒中の理学療法 第3版", authors: "原寛美 編著", publisher: "医学書院", year: 2021, price: "¥5,500", coverUrl: "", keywords: ["脳卒中", "片麻痺", "stroke", "脳梗塞", "脳出血", "神経"], summary: "脳卒中リハビリテーションの基礎から臨床応用まで体系的に解説。評価・治療の根拠をエビデンスとともに学べる。片麻痺患者の運動機能回復に関わるPTに必携の参考書です。" },
  { id: "b2",  category: "neuro",    title: "神経系理学療法学 改訂第2版", authors: "奈良勲 監修", publisher: "メジカルビュー社", year: 2020, price: "¥6,600", coverUrl: "", keywords: ["神経", "パーキンソン", "脊髄損傷", "神経疾患", "脳卒中"], summary: "神経疾患リハビリテーションの理論と実践技術を網羅。パーキンソン病・脊髄損傷・多発性硬化症など幅広い疾患に対応。国試にも対応した体系的学習に役立ちます。" },
  { id: "b3",  category: "neuro",    title: "脳卒中理学療法の理論と技術 改訂第3版", authors: "石川誠 監修", publisher: "メジカルビュー社", year: 2022, price: "¥7,700", coverUrl: "", keywords: ["脳卒中", "片麻痺", "歩行", "上肢", "ADL", "FIM"], summary: "脳卒中リハの理論的根拠と具体的技術を豊富なイラスト・写真で解説。急性期から生活期まで段階別のアプローチを網羅しており、新人PTから経験者まで活用できます。" },
  { id: "b4",  category: "neuro",    title: "パーキンソン病のリハビリテーション 第2版", authors: "服部信孝 監修", publisher: "南江堂", year: 2021, price: "¥4,950", coverUrl: "", keywords: ["パーキンソン", "神経", "歩行", "凍結", "姿勢"], summary: "パーキンソン病リハの最新エビデンスをもとに実践的なアプローチを解説。歩行訓練・バランス訓練・ADL支援・患者・家族指導まで網羅した一冊です。" },
  { id: "b5",  category: "neuro",    title: "脊髄損傷リハビリテーション 最新の実際", authors: "緒方甫 著", publisher: "三輪書店", year: 2020, price: "¥6,380", coverUrl: "", keywords: ["脊髄損傷", "SCI", "対麻痺", "四肢麻痺", "FIM"], summary: "脊髄損傷の病態から機能回復・福祉用具・地域生活支援まで包括的に解説。AISのレベル別アプローチや歩行訓練・車椅子操作訓練の詳細が充実しています。" },
  { id: "b6",  category: "neuro",    title: "神経可塑性とリハビリテーション", authors: "道免和久 編著", publisher: "医学書院", year: 2023, price: "¥5,280", coverUrl: "", keywords: ["神経可塑性", "脳卒中", "回復", "neuroplasticity", "学習"], summary: "神経可塑性の基礎科学から臨床応用まで最新知見を解説。CI療法・ロボット支援・経頭蓋刺激など新治療技術の理論的背景を学べる先進的な参考書です。" },
  { id: "b7",  category: "neuro",    title: "脳卒中評価スケール完全ガイド", authors: "長谷川恒雄 著", publisher: "羊土社", year: 2022, price: "¥4,400", coverUrl: "", keywords: ["評価", "脳卒中", "FIM", "BRS", "mRS", "NIHSS", "FMA"], summary: "脳卒中リハで使用する全評価スケールを完全収録。実施方法・採点基準・信頼性・妥当性・活用場面を詳解。日々の臨床ですぐ使えるリファレンスブックです。" },
  { id: "b8",  category: "neuro",    title: "高次脳機能障害のリハビリテーション 第2版", authors: "橋本圭司 著", publisher: "医学書院", year: 2021, price: "¥5,940", coverUrl: "", keywords: ["高次脳機能", "失語", "失行", "失認", "注意", "記憶"], summary: "注意障害・記憶障害・失語・遂行機能障害など高次脳機能障害のリハビリを詳解。評価方法・介入技術・職場復帰支援・家族指導まで実践的内容が充実しています。" },
  { id: "b9",  category: "neuro",    title: "嚥下リハビリテーション 標準テキスト", authors: "藤島一郎 監修", publisher: "医歯薬出版", year: 2020, price: "¥6,600", coverUrl: "", keywords: ["嚥下", "摂食嚥下", "脳卒中", "誤嚥", "dysphagia"], summary: "摂食嚥下障害の評価・訓練・食形態調整・チームアプローチを体系的に解説。VF・VE検査の読み方から間接・直接訓練の技術まで実践に直結した内容です。" },
  { id: "b10", category: "neuro",    title: "臨床神経学 理学療法士のための基礎テキスト", authors: "上田敏 著", publisher: "医学書院", year: 2019, price: "¥4,950", coverUrl: "", keywords: ["神経学", "解剖", "神経", "基礎", "脳", "脊髄"], summary: "理学療法士が臨床で必要な神経学的知識をわかりやすく解説。神経解剖・生理・疾患概論・評価の基礎を網羅し、神経系リハの理解を深める土台となる一冊です。" },

  // ── 運動器・整形外科（10冊）──────────────────────────────
  { id: "b11", category: "ortho",    title: "整形外科理学療法の理論と技術 改訂第2版", authors: "山嵜勉 編著", publisher: "メジカルビュー社", year: 2019, price: "¥7,700", coverUrl: "", keywords: ["整形外科", "運動器", "膝", "股関節", "肩", "腰椎", "骨折"], summary: "運動器疾患における評価・治療の理論的根拠を丁寧に解説。各関節の機能解剖から疾患別アプローチまで実践的に学べます。整形外科領域で働くPTの必携書です。" },
  { id: "b12", category: "ortho",    title: "運動器疾患の理学療法 第2版", authors: "松本秀男 著", publisher: "三輪書店", year: 2022, price: "¥5,280", coverUrl: "", keywords: ["運動器", "骨折", "変形性", "関節", "靭帯", "腱", "スポーツ"], summary: "変形性関節症・骨折後リハ・スポーツ障害など運動器疾患の理学療法を詳説。評価からゴール設定・退院支援まで臨床フローに沿って学べる構成です。" },
  { id: "b13", category: "ortho",    title: "スポーツ理学療法の理論と実際", authors: "津田英一 編著", publisher: "南江堂", year: 2023, price: "¥6,600", coverUrl: "", keywords: ["スポーツ", "投球障害", "野球肩", "ACL", "スポーツ外傷", "スポーツリハ", "野球"], summary: "投球障害・下肢外傷・スポーツ復帰判定など競技別・疾患別に解説。科学的評価・予防トレーニング・スポーツ復帰基準を体系的に学べる決定版テキストです。" },
  { id: "b14", category: "ortho",    title: "肩関節のリハビリテーション 第4版", authors: "高橋憲正 著", publisher: "メジカルビュー社", year: 2021, price: "¥5,940", coverUrl: "", keywords: ["肩", "肩関節", "腱板", "インピンジメント", "投球", "野球肩", "凍結肩"], summary: "肩関節疾患のリハビリを機能解剖から丁寧に解説。腱板損傷・インピンジメント・凍結肩・投球障害など主要疾患の評価・治療手技を豊富な写真で示した実践書です。" },
  { id: "b15", category: "ortho",    title: "膝関節のリハビリテーション 改訂2版", authors: "黒澤尚 監修", publisher: "メジカルビュー社", year: 2022, price: "¥5,500", coverUrl: "", keywords: ["膝", "変形性膝関節症", "TKA", "ACL", "半月板", "靭帯"], summary: "膝関節疾患の評価・リハビリテーション技術を網羅。変形性膝関節症・ACL損傷・TKA後リハなど症例に応じた段階的プログラムが充実しています。" },
  { id: "b16", category: "ortho",    title: "腰椎のリハビリテーション エビデンスと実践", authors: "相澤純也 著", publisher: "医学書院", year: 2023, price: "¥5,280", coverUrl: "", keywords: ["腰椎", "腰痛", "腰部脊柱管狭窄症", "椎間板ヘルニア", "体幹"], summary: "腰椎疾患リハの最新エビデンスと実践技術を統合した参考書。腰痛のバイオサイコソーシャルモデルから各疾患別アプローチまで科学的に解説しています。" },
  { id: "b17", category: "ortho",    title: "スポーツ外傷・障害の理学療法 改訂版", authors: "木村菜穂子 編著", publisher: "三輪書店", year: 2020, price: "¥4,950", coverUrl: "", keywords: ["スポーツ外傷", "スポーツ障害", "野球肩", "投球障害", "足関節", "ACL"], summary: "スポーツ現場で遭遇する外傷・障害の評価から復帰判定まで実践的に解説。投球障害・ACL損傷・足関節捻挫など競技種目別のアプローチが充実しています。" },
  { id: "b18", category: "ortho",    title: "手の外科リハビリテーション 第3版", authors: "田中克己 著", publisher: "金原出版", year: 2021, price: "¥6,050", coverUrl: "", keywords: ["手", "指", "手外科", "腱", "手根管", "ROM", "握力"], summary: "手の解剖から疾患別リハビリテーションまで詳細に解説。腱損傷・骨折・手根管症候群・関節リウマチなど手外科疾患の評価・治療を体系的に学べます。" },
  { id: "b19", category: "ortho",    title: "変形性股関節症のリハビリテーション", authors: "二木康之 著", publisher: "南江堂", year: 2022, price: "¥4,620", coverUrl: "", keywords: ["股関節", "変形性股関節症", "THA", "human hip", "骨切り"], summary: "変形性股関節症の病態から手術療法・理学療法まで網羅。THA後リハビリのプロトコルや日常生活指導・再発予防策まで実践的内容が充実しています。" },
  { id: "b20", category: "ortho",    title: "足・足関節のリハビリテーション 改訂版", authors: "出村博 著", publisher: "医歯薬出版", year: 2020, price: "¥4,840", coverUrl: "", keywords: ["足", "足関節", "足底筋膜炎", "捻挫", "ankle", "アキレス腱"], summary: "足・足関節の機能解剖から疾患別リハビリテーションを解説。足底筋膜炎・アキレス腱損傷・足関節捻挫・外反母趾など日常臨床で役立つ内容を網羅しています。" },

  // ── 内部障害・循環器（10冊）──────────────────────────────
  { id: "b21", category: "internal", title: "内部障害理学療法学 第4版", authors: "上月正博 監修", publisher: "医歯薬出版", year: 2022, price: "¥6,820", coverUrl: "", keywords: ["内部障害", "心臓", "心不全", "循環器", "糖尿病", "腎臓", "cardiac"], summary: "心疾患・慢性腎臓病・糖尿病など内部障害を持つ患者のリハビリ理論と実践を網羅。最新エビデンスに基づいた心臓リハ・CKDリハの解説が充実しています。" },
  { id: "b22", category: "internal", title: "心臓リハビリテーション実践マニュアル 改訂版", authors: "里見淳一郎 著", publisher: "南江堂", year: 2023, price: "¥5,940", coverUrl: "", keywords: ["心臓リハ", "cardiac rehab", "心筋梗塞", "心不全", "有酸素", "CPX"], summary: "心臓リハビリテーションの理論と実践を完全網羅。CPX・AT・運動処方の実際から患者教育・リスク管理まで現場即応の内容が充実した決定版マニュアルです。" },
  { id: "b23", category: "internal", title: "糖尿病のリハビリテーション 最新の理論と実際", authors: "田中喜代次 著", publisher: "医学書院", year: 2021, price: "¥4,950", coverUrl: "", keywords: ["糖尿病", "diabetes", "運動療法", "HbA1c", "内部障害", "血糖"], summary: "糖尿病患者の運動療法・生活指導・合併症予防を体系的に解説。血糖コントロールのメカニズムから安全な運動実施法・患者教育まで臨床で即使える内容です。" },
  { id: "b24", category: "internal", title: "心不全リハビリテーション 理論と実践", authors: "宮内重人 著", publisher: "羊土社", year: 2022, price: "¥5,280", coverUrl: "", keywords: ["心不全", "heart failure", "循環器", "心臓リハ", "BNP", "QOL"], summary: "慢性心不全患者のリハビリテーション全般を解説。機能評価・運動処方・リスク管理・退院支援・地域連携まで実践的視点で学べる実用的な参考書です。" },
  { id: "b25", category: "internal", title: "慢性腎臓病（CKD）のリハビリテーション", authors: "池田隆徳 監修", publisher: "メジカルビュー社", year: 2023, price: "¥4,620", coverUrl: "", keywords: ["腎臓", "CKD", "透析", "腎リハ", "内部障害"], summary: "CKD・透析患者への運動療法の理論とエビデンスを詳解。安全な運動実施のためのリスク管理・評価方法・運動処方・患者指導まで実践的内容が充実しています。" },
  { id: "b26", category: "internal", title: "がんリハビリテーション 理学療法士のための実践テキスト", authors: "辻哲也 著", publisher: "医学書院", year: 2022, price: "¥6,600", coverUrl: "", keywords: ["がん", "cancer", "腫瘍", "内部障害", "倦怠感", "サルコペニア"], summary: "がん患者のリハビリテーション全般を解説。がん関連倦怠感・サルコペニア・がん性疼痛・術後リハ・緩和ケアまで幅広い内容をエビデンスとともに学べます。" },
  { id: "b27", category: "internal", title: "生活習慣病と運動療法", authors: "井出肇 著", publisher: "南江堂", year: 2021, price: "¥4,180", coverUrl: "", keywords: ["生活習慣病", "糖尿病", "高血圧", "肥満", "メタボ", "内部障害"], summary: "高血圧・糖尿病・脂質異常症・メタボリックシンドロームに対する運動療法を詳解。疾患別の運動処方・安全管理・患者指導を実践的に学べます。" },
  { id: "b28", category: "internal", title: "ICU・急性期リハビリテーション 実践テキスト", authors: "山本寛 著", publisher: "三輪書店", year: 2023, price: "¥5,500", coverUrl: "", keywords: ["ICU", "急性期", "重症", "廃用", "早期離床", "人工呼吸器"], summary: "ICU・急性期病棟でのリハビリテーションを体系的に解説。早期離床の適応・禁忌・実施手順・評価から人工呼吸器患者への対応まで現場即応の内容です。" },
  { id: "b29", category: "internal", title: "透析患者のリハビリテーション 改訂版", authors: "長坂誠 著", publisher: "医歯薬出版", year: 2020, price: "¥4,400", coverUrl: "", keywords: ["透析", "腎臓", "内部障害", "CKD", "運動療法"], summary: "血液透析・腹膜透析患者へのリハビリテーションを解説。透析中・透析間の運動療法・ADL指導・生活指導を安全に実施するための実践的内容が充実しています。" },
  { id: "b30", category: "internal", title: "ロコモティブシンドロームの予防とリハビリ", authors: "石橋英明 著", publisher: "南江堂", year: 2022, price: "¥3,960", coverUrl: "", keywords: ["ロコモ", "サルコペニア", "フレイル", "高齢者", "転倒", "予防"], summary: "ロコモティブシンドローム・サルコペニア・フレイルの予防とリハビリを解説。評価方法・運動処方・生活指導・地域連携まで実践的に学べます。" },

  // ── 呼吸器（10冊）───────────────────────────────────────
  { id: "b31", category: "resp",     title: "呼吸リハビリテーション 実践テキスト", authors: "日本呼吸ケア・リハビリテーション学会 監修", publisher: "南江堂", year: 2021, price: "¥5,940", coverUrl: "", keywords: ["呼吸", "COPD", "肺", "呼吸器", "respiratory", "在宅酸素"], summary: "COPD・間質性肺疾患・慢性呼吸不全など呼吸器疾患のリハビリ手技を実践的に解説。コンディショニングから栄養・ADL指導まで包括的に学べます。" },
  { id: "b32", category: "resp",     title: "COPDのリハビリテーション 第2版", authors: "木田厚瑞 監修", publisher: "医学書院", year: 2022, price: "¥5,280", coverUrl: "", keywords: ["COPD", "肺リハ", "呼吸器", "6MWT", "SGRQ", "呼吸筋"], summary: "COPD患者の肺リハビリテーションを最新エビデンスで解説。呼吸訓練・運動療法・患者教育・栄養管理・急性増悪対応まで包括的なアプローチを学べます。" },
  { id: "b33", category: "resp",     title: "呼吸機能検査の読み方と理学療法への応用", authors: "小林悠樹 著", publisher: "羊土社", year: 2023, price: "¥4,620", coverUrl: "", keywords: ["呼吸機能", "スパイロ", "FVC", "FEV1", "呼吸器", "肺機能"], summary: "スパイロメトリーをはじめとする呼吸機能検査の結果の読み方と理学療法への応用を解説。各検査値の意味・疾患別パターン・運動処方への活かし方を詳解します。" },
  { id: "b34", category: "resp",     title: "間質性肺疾患のリハビリテーション", authors: "坂本雄一 著", publisher: "メジカルビュー社", year: 2022, price: "¥4,950", coverUrl: "", keywords: ["間質性肺炎", "ILD", "IPF", "呼吸器", "肺線維症", "6MWT"], summary: "間質性肺疾患（IPF・過敏性肺炎など）のリハビリテーション理論と実践を解説。酸素療法下での運動療法・呼吸訓練・ADL指導・緩和的アプローチまで学べます。" },
  { id: "b35", category: "resp",     title: "周術期呼吸リハビリテーション 最新ガイド", authors: "永田一真 著", publisher: "三輪書店", year: 2021, price: "¥4,840", coverUrl: "", keywords: ["周術期", "術前", "術後", "呼吸器", "肺切除", "横隔膜", "呼吸訓練"], summary: "肺切除術・心臓手術・腹部手術など周術期の呼吸リハビリを解説。術前評価・術後合併症予防・呼吸訓練の実際・ICU でのリハビリ実施方法まで学べます。" },
  { id: "b36", category: "resp",     title: "在宅呼吸ケアガイドブック 改訂版", authors: "丸山和典 著", publisher: "南江堂", year: 2020, price: "¥3,960", coverUrl: "", keywords: ["在宅", "HOT", "NPPV", "TPPV", "呼吸器", "在宅酸素"], summary: "在宅酸素療法（HOT）・非侵襲的人工換気（NPPV）患者のリハビリと在宅ケアを解説。機器管理・緊急時対応・家族指導・訪問理学療法の実際を網羅しています。" },
  { id: "b37", category: "resp",     title: "急性呼吸不全のリハビリテーション", authors: "津田亮 著", publisher: "医歯薬出版", year: 2023, price: "¥5,280", coverUrl: "", keywords: ["急性期", "ARDS", "呼吸不全", "ICU", "人工呼吸器", "早期離床"], summary: "ARDS・急性呼吸不全患者への急性期リハビリテーションを解説。人工呼吸器装着中の早期離床・呼吸理学療法・廃用予防の具体的手技と安全基準を学べます。" },
  { id: "b38", category: "resp",     title: "呼吸理学療法テクニック 完全マスター", authors: "有山雅 著", publisher: "羊土社", year: 2022, price: "¥4,400", coverUrl: "", keywords: ["呼吸理学療法", "排痰", "体位ドレナージ", "スクイージング", "呼吸補助"], summary: "排痰法・スクイージング・体位ドレナージ・呼吸補助手技など呼吸理学療法の技術を写真・動画QR付きで詳解。手技の根拠・適応・注意事項まで体系的に学べます。" },
  { id: "b39", category: "resp",     title: "慢性呼吸器疾患の栄養・運動療法", authors: "桑野太朗 著", publisher: "メジカルビュー社", year: 2021, price: "¥4,180", coverUrl: "", keywords: ["栄養", "呼吸器", "COPD", "低栄養", "サルコペニア"], summary: "COPD・間質性肺疾患患者の低栄養・筋肉量減少（サルコペニア）への栄養・運動療法を解説。医師・管理栄養士との連携のあり方も具体的に学べます。" },
  { id: "b40", category: "resp",     title: "喘息のリハビリテーションと生活指導", authors: "吾妻義則 著", publisher: "南江堂", year: 2020, price: "¥3,740", coverUrl: "", keywords: ["喘息", "気管支喘息", "呼吸器", "アレルギー", "吸入"], summary: "気管支喘息患者への呼吸リハビリテーションと生活指導を解説。自己管理・トリガー回避・呼吸訓練・運動制限のある患者への対応まで実践的に学べます。" },

  // ── 小児リハ（10冊）──────────────────────────────────────
  { id: "b41", category: "peds",     title: "小児理学療法学テキスト 改訂第3版", authors: "加藤寿宏 編著", publisher: "南江堂", year: 2020, price: "¥6,380", coverUrl: "", keywords: ["小児", "脳性麻痺", "発達", "子ども", "pediatrics", "二分脊椎"], summary: "脳性麻痺・発達障害・二分脊椎など小児疾患のリハビリを体系的に解説。発達段階に応じた評価・介入方法を豊富なイラストでわかりやすく説明しています。" },
  { id: "b42", category: "peds",     title: "脳性麻痺リハビリテーション 最新アプローチ", authors: "稲田雅也 著", publisher: "医学書院", year: 2022, price: "¥5,500", coverUrl: "", keywords: ["脳性麻痺", "CP", "小児", "片麻痺", "痙直", "GMFCS"], summary: "脳性麻痺の評価・治療・装具療法・補装具・手術療法との連携まで最新のエビデンスをもとに解説。GMFCS別のゴール設定と介入プログラムが充実しています。" },
  { id: "b43", category: "peds",     title: "発達障害児の理学療法 DCD・ASD・ADHDへの対応", authors: "高橋まゆみ 著", publisher: "三輪書店", year: 2023, price: "¥4,840", coverUrl: "", keywords: ["発達障害", "DCD", "ASD", "ADHD", "小児", "感覚統合"], summary: "発達性協調運動障害（DCD）・ASD・ADHDなど発達障害児への理学療法アプローチを解説。感覚統合理論・認知アプローチ・環境調整まで実践的内容が充実しています。" },
  { id: "b44", category: "peds",     title: "小児の整形外科的疾患と理学療法", authors: "星文彦 著", publisher: "メジカルビュー社", year: 2021, price: "¥5,280", coverUrl: "", keywords: ["小児", "先天性股関節脱臼", "ペルテス", "側弯", "成長", "小児整形"], summary: "先天性股関節脱臼・ペルテス病・Blount病・側弯症など小児整形外科疾患のリハビリを解説。各疾患の病態・装具療法・手術後リハを体系的に学べます。" },
  { id: "b45", category: "peds",     title: "NICU退院後の発達支援 フォローアップのために", authors: "前川喜平 監修", publisher: "南江堂", year: 2022, price: "¥4,620", coverUrl: "", keywords: ["NICU", "早産", "低出生体重", "発達支援", "小児", "フォローアップ"], summary: "NICU退院後の極低出生体重児・早産児へのフォローアップと発達支援を解説。運動発達評価・理学療法介入・家族支援・多職種連携の実際を詳細に学べます。" },
  { id: "b46", category: "peds",     title: "子どものスポーツ外傷と理学療法", authors: "田中陽平 著", publisher: "羊土社", year: 2023, price: "¥4,400", coverUrl: "", keywords: ["小児", "スポーツ", "オスグッド", "骨端症", "スポーツ障害", "野球肘"], summary: "オスグッド病・野球肘・シーバー病など小児スポーツ障害のリハビリを解説。成長期特有の特徴を踏まえた評価・介入・復帰判定・予防指導を学べます。" },
  { id: "b47", category: "peds",     title: "発達の評価と支援 理学療法士のための実践テキスト", authors: "北義子 著", publisher: "医歯薬出版", year: 2021, price: "¥4,950", coverUrl: "", keywords: ["発達評価", "GMFM", "小児", "発達", "評価", "PEDI"], summary: "GMFM・PEDI・WeeFIM・Alberta乳幼児運動スケールなど小児の発達評価ツールを詳解。評価の目的・実施方法・採点・活用方法を実践的に学べる参考書です。" },
  { id: "b48", category: "peds",     title: "二分脊椎症のリハビリテーション", authors: "坂本祥一 著", publisher: "三輪書店", year: 2020, price: "¥4,840", coverUrl: "", keywords: ["二分脊椎", "脊髄髄膜瘤", "小児", "排泄", "歩行", "車椅子"], summary: "二分脊椎症の各種病態・評価・リハビリテーション・装具療法・泌尿器合併症管理・ライフステージ別支援を包括的に解説した専門テキストです。" },
  { id: "b49", category: "peds",     title: "ダウン症候群のリハビリテーション 改訂版", authors: "清水眞理子 著", publisher: "南江堂", year: 2022, price: "¥4,180", coverUrl: "", keywords: ["ダウン症", "染色体", "知的障害", "小児", "ハイパーモビリティ"], summary: "ダウン症候群の発達特性・評価・理学療法介入・家庭プログラム指導を解説。特有の筋低緊張・関節弛緩性への対応から、学校・就労への移行支援まで学べます。" },
  { id: "b50", category: "peds",     title: "在宅医療と小児リハビリテーション", authors: "杉本健郎 著", publisher: "医学書院", year: 2021, price: "¥4,620", coverUrl: "", keywords: ["在宅", "小児", "医療的ケア", "訪問リハ", "重症心身障害"], summary: "医療的ケア児・重症心身障害児への在宅訪問リハビリを解説。評価・プログラム立案・家族指導・チームアプローチ・地域資源活用まで実践的に学べます。" },

  // ── 評価・測定（10冊）────────────────────────────────────
  { id: "b51", category: "eval",     title: "理学療法評価学 第4版", authors: "奈良勲 監修", publisher: "医歯薬出版", year: 2022, price: "¥5,500", coverUrl: "", keywords: ["評価", "MMT", "ROM", "FIM", "BBS", "測定", "スケール"], summary: "MMT・ROM・FIM・BBS・10m歩行など臨床でよく使う評価スケールを網羅。評価の目的・手順・判定基準・信頼性・妥当性を丁寧に解説しています。" },
  { id: "b52", category: "eval",     title: "関節可動域測定法 改訂版 完全ガイド", authors: "平澤泰介 著", publisher: "羊土社", year: 2023, price: "¥4,620", coverUrl: "", keywords: ["ROM", "関節可動域", "測定", "ゴニオメーター", "評価"], summary: "全関節の可動域測定法を写真・イラスト付きで詳解。測定肢位・基準軸・移動軸・注意点・検者内・検者間信頼性まで体系的に学べる必携リファレンスです。" },
  { id: "b53", category: "eval",     title: "徒手筋力検査法（MMT）完全マスター", authors: "角田亘 著", publisher: "南江堂", year: 2022, price: "¥4,400", coverUrl: "", keywords: ["MMT", "筋力", "徒手筋力", "評価", "テスト"], summary: "全筋の徒手筋力検査法を詳解。各筋の解剖・神経支配・テスト肢位・代償動作への対応・臨床での活用法まで系統的に学べる完全マスターシリーズです。" },
  { id: "b54", category: "eval",     title: "歩行分析 ビジュアル理学療法評価学", authors: "月城慶一 監修", publisher: "メジカルビュー社", year: 2021, price: "¥5,940", coverUrl: "", keywords: ["歩行分析", "歩行", "バランス", "評価", "TUG", "10m歩行"], summary: "正常歩行から病的歩行まで視覚的・系統的に解説。三次元動作解析の基礎から目視での歩行分析技術まで、臨床で即活かせる内容を豊富な写真と図で示しています。" },
  { id: "b55", category: "eval",     title: "バランス評価スケール実践ガイド", authors: "吉田剛 著", publisher: "三輪書店", year: 2023, price: "¥4,180", coverUrl: "", keywords: ["バランス", "BBS", "TUG", "転倒", "評価", "平衡機能"], summary: "BBS・TUG・FAB・Mini-BESTest・FSST など主要バランス評価スケールを完全収録。各スケールの実施手順・採点法・解釈・カットオフ値・転倒予測能を詳解します。" },
  { id: "b56", category: "eval",     title: "ADL・QOL評価スケール大全", authors: "土屋貴子 著", publisher: "医歯薬出版", year: 2022, price: "¥4,950", coverUrl: "", keywords: ["FIM", "BI", "ADL", "QOL", "評価", "IADL", "SF-36"], summary: "FIM・Barthel Index・SF-36・EQ-5D など主要ADL・QOL評価スケールを詳解。使用目的・測定内容・信頼性・妥当性・反応性を比較できる便利なリファレンスです。" },
  { id: "b57", category: "eval",     title: "呼吸・循環機能評価の実際", authors: "笠井靖代 著", publisher: "南江堂", year: 2021, price: "¥4,620", coverUrl: "", keywords: ["呼吸機能", "心拍数", "SpO2", "6MWT", "CPX", "評価", "心臓リハ"], summary: "SpO2モニタリング・6MWT・CPX・心エコーの読み方など呼吸・循環機能評価を解説。運動中のモニタリング方法・異常値への対応まで安全な運動療法実施に必要な知識を学べます。" },
  { id: "b58", category: "eval",     title: "疼痛評価の実践 NRS・VAS・痛みの地図", authors: "田口芳雄 著", publisher: "三輪書店", year: 2020, price: "¥3,740", coverUrl: "", keywords: ["疼痛評価", "NRS", "VAS", "FPS", "痛み", "評価"], summary: "NRS・VAS・FPS・BPI・PainDETECT など疼痛評価ツールの使い方を詳解。急性痛・慢性痛・神経障害性疼痛の評価の違いと適切なスケール選択を学べます。" },
  { id: "b59", category: "eval",     title: "認知機能評価の実際 MMSE・HDS-R・MoCA", authors: "橋本衛 著", publisher: "医学書院", year: 2023, price: "¥4,180", coverUrl: "", keywords: ["認知機能", "MMSE", "HDS-R", "MoCA", "評価", "認知症", "スクリーニング"], summary: "MMSE・HDS-R・MoCA・CDRなど認知機能評価スケールを詳解。実施方法・採点・解釈・リハビリとの関連・認知症スクリーニングへの活用まで実践的に学べます。" },
  { id: "b60", category: "eval",     title: "栄養・体組成評価とリハビリへの応用", authors: "真田弘美 著", publisher: "南江堂", year: 2022, price: "¥4,400", coverUrl: "", keywords: ["栄養", "体組成", "サルコペニア", "BIA", "MNA", "評価"], summary: "栄養スクリーニング・体組成測定（BIA）・サルコペニア評価（AWGS基準）などをリハビリに活かすための実践的知識を解説。栄養リハビリの実際まで学べます。" },

  // ── 解剖学・生理学（10冊）───────────────────────────────
  { id: "b61", category: "anatomy",  title: "解剖学 第23版（系統看護学講座）", authors: "藤田恒夫 著", publisher: "医学書院", year: 2022, price: "¥4,400", coverUrl: "", keywords: ["解剖", "骨", "筋", "神経", "解剖学", "anatomy"], summary: "PTの臨床に必要な解剖学の知識をコンパクトにまとめた定番教科書。骨・筋・神経・循環器など各系統の解剖をイラストと写真で視覚的に学べます。" },
  { id: "b62", category: "anatomy",  title: "プロメテウス解剖学アトラス 総論・運動器系 第3版", authors: "シュンケ M 著", publisher: "医学書院", year: 2021, price: "¥9,900", coverUrl: "", keywords: ["解剖学", "アトラス", "筋", "骨", "関節", "運動器"], summary: "カラーイラストによる詳細な解剖学アトラス。運動器系の骨・関節・靭帯・筋を精密なイラストで視覚的に学べる世界標準のリファレンスです。" },
  { id: "b63", category: "anatomy",  title: "運動学 理学療法士のための実践テキスト 改訂版", authors: "小林量作 編著", publisher: "南江堂", year: 2022, price: "¥5,280", coverUrl: "", keywords: ["運動学", "biomechanics", "関節力学", "歩行", "筋収縮"], summary: "理学療法士に必要な運動学的知識を体系的に解説。関節の運動・筋の機能・歩行の力学・運動処方の根拠まで、臨床思考の基礎を形成する重要テキストです。" },
  { id: "b64", category: "anatomy",  title: "筋骨格系のキネシオロジー 原著第3版", authors: "ドナルド A ノイマン 著", publisher: "医歯薬出版", year: 2018, price: "¥12,100", coverUrl: "", keywords: ["キネシオロジー", "運動学", "筋骨格", "機能解剖", "関節", "biomechanics"], summary: "筋骨格系の機能解剖を徹底解説した世界的名著。各関節の構造・運動・筋の機能と協調をわかりやすく解説。豊富なカラーイラストで視覚的に理解できます。" },
  { id: "b65", category: "anatomy",  title: "神経解剖学 理学療法士のための基礎と臨床", authors: "後藤文男 著", publisher: "医学書院", year: 2020, price: "¥5,500", coverUrl: "", keywords: ["神経解剖", "脳", "脊髄", "神経", "伝導路", "反射"], summary: "脳・脊髄・末梢神経の解剖学を理学療法士の視点で解説。伝導路・反射弓・高次脳機能の解剖学的基礎まで、神経系リハビリの理解に必要な知識を体系的に学べます。" },
  { id: "b66", category: "anatomy",  title: "生理学 理学療法士のための実践基礎", authors: "岸田克哉 著", publisher: "南江堂", year: 2021, price: "¥4,400", coverUrl: "", keywords: ["生理学", "筋収縮", "心臓", "呼吸", "神経生理"], summary: "PTの臨床に直結する生理学的知識を実践的に解説。筋収縮のメカニズム・心肺機能・神経生理・代謝の基礎まで、リハビリの科学的根拠を理解するための基礎テキストです。" },
  { id: "b67", category: "anatomy",  title: "体表解剖学 触診技術の基礎と実践", authors: "竹田節子 著", publisher: "三輪書店", year: 2023, price: "¥4,620", coverUrl: "", keywords: ["触診", "体表解剖", "骨標識", "筋", "解剖", "触診技術"], summary: "全身の骨標識・筋・腱・靭帯・神経・血管の触診法を詳解。正確な触診のための体表解剖の知識と実際の手技を写真とイラストで学べる実践的参考書です。" },
  { id: "b68", category: "anatomy",  title: "呼吸・循環の生理学 改訂版", authors: "小川聡 著", publisher: "医学書院", year: 2020, price: "¥4,180", coverUrl: "", keywords: ["呼吸生理", "循環生理", "心臓", "肺", "ガス交換", "心拍出量"], summary: "呼吸・循環の生理学的基礎を理学療法士の視点で解説。換気・ガス交換・心拍出量・運動時の生理的変化まで、内部障害リハの科学的背景を学べます。" },
  { id: "b69", category: "anatomy",  title: "運動生理学 スポーツ・リハビリへの応用 第3版", authors: "勝田茂 著", publisher: "朝倉書店", year: 2022, price: "¥4,840", coverUrl: "", keywords: ["運動生理", "VO2max", "エネルギー代謝", "持久力", "筋肥大"], summary: "運動生理学の基礎から臨床・スポーツへの応用まで解説。VO2max・乳酸閾値・筋疲労・エネルギー代謝・運動処方の科学的根拠を体系的に学べます。" },
  { id: "b70", category: "anatomy",  title: "バイオメカニクス入門 理学療法への応用", authors: "金子唯史 著", publisher: "医歯薬出版", year: 2021, price: "¥3,960", coverUrl: "", keywords: ["バイオメカニクス", "力学", "歩行", "運動学", "重心", "床反力"], summary: "力学の基礎から歩行・動作分析への応用まで解説。床反力・重心・モーメント・筋張力の計算と臨床への活かし方を、わかりやすい図解で学べる入門テキストです。" },

  // ── 国家試験対策（10冊）──────────────────────────────────
  { id: "b71", category: "exam",     title: "PT・OT国家試験 必修ポイント 2024年版", authors: "羊土社 編集", publisher: "羊土社", year: 2023, price: "¥3,960", coverUrl: "", keywords: ["国家試験", "国試", "PT", "OT", "試験", "問題集"], summary: "理学療法士・作業療法士国家試験の頻出ポイントを効率よく学べる問題集。過去問傾向分析をもとに重要項目を厳選し、短時間での合格力養成をサポートします。" },
  { id: "b72", category: "exam",     title: "理学療法士国家試験 完全攻略 2024", authors: "長谷公隆 監修", publisher: "医学書院", year: 2023, price: "¥4,620", coverUrl: "", keywords: ["国家試験", "PT", "理学療法士", "過去問", "模擬試験"], summary: "PT国試の全分野を網羅した完全攻略テキスト。頻出問題・重要事項・解説を凝縮し、弱点分野の補強と得点力向上を効率的に実現できます。" },
  { id: "b73", category: "exam",     title: "クエスチョン・バンク PT国試 全問解説 2024", authors: "医療情報科学研究所 編", publisher: "メディックメディア", year: 2023, price: "¥5,280", coverUrl: "", keywords: ["国家試験", "PT", "過去問解説", "国試", "理学療法"], summary: "過去10年分のPT国試問題を全問詳細解説。問題別の重要度・関連知識・解法のポイントを体系的に整理。繰り返し解くことで確実な知識定着を図れます。" },
  { id: "b74", category: "exam",     title: "理学療法士 国家試験問題集 解説付き 2024年版", authors: "穂稿社 編", publisher: "南江堂", year: 2023, price: "¥3,740", coverUrl: "", keywords: ["国家試験", "問題集", "PT", "解説", "国試対策"], summary: "直近5年分の国試問題と詳細解説を収録。分野別インデックス・重要図表・覚えやすいゴロ合わせで効率的な学習が可能。模擬試験形式でも使えます。" },
  { id: "b75", category: "exam",     title: "PT・OT国試必携 解剖学・生理学 重点整理", authors: "田中信孝 著", publisher: "三輪書店", year: 2023, price: "¥3,300", coverUrl: "", keywords: ["国家試験", "解剖学", "生理学", "国試", "PT", "基礎医学"], summary: "PT・OT国試に頻出の解剖学・生理学を重点整理。覚えるべき数値・構造・機能をシンプルな図表で整理し、直前対策にも活用できる効率的な参考書です。" },
  { id: "b76", category: "exam",     title: "PT国試 臨床医学まとめノート", authors: "中川法一 監修", publisher: "羊土社", year: 2022, price: "¥3,520", coverUrl: "", keywords: ["国家試験", "臨床医学", "内科", "整形外科", "神経", "PT国試"], summary: "PT国試の臨床医学系問題を効率よく攻略するまとめノート。各疾患の概要・症状・検査・治療の要点を簡潔にまとめ、短時間での知識確認に最適です。" },
  { id: "b77", category: "exam",     title: "理学療法士国試 計算問題・グラフ問題 完全攻略", authors: "和田弘太郎 著", publisher: "医歯薬出版", year: 2023, price: "¥2,860", coverUrl: "", keywords: ["国家試験", "計算問題", "グラフ", "PT", "国試対策"], summary: "苦手な人が多い計算問題・グラフ問題を徹底解説。出題パターン別に解法を詳しく説明し、過去問演習で確実に得点できる力を身につけられます。" },
  { id: "b78", category: "exam",     title: "PT国試 新傾向問題 予想と対策 2024", authors: "飯田泰治 著", publisher: "南江堂", year: 2023, price: "¥3,300", coverUrl: "", keywords: ["国家試験", "新傾向", "PT", "国試", "予想問題"], summary: "最新の国試傾向を分析した予想問題集。社会保障・介護保険・地域医療など新傾向問題を中心に収録し、苦手分野の補強と得点力向上を効率的に実現できます。" },
  { id: "b79", category: "exam",     title: "PT・OT国試 専門基礎分野 完全マスター", authors: "安藤大輔 著", publisher: "三輪書店", year: 2022, price: "¥3,960", coverUrl: "", keywords: ["国家試験", "専門基礎", "PT", "OT", "運動学", "解剖", "生理"], summary: "運動学・解剖学・生理学・臨床医学の専門基礎分野を完全網羅。イラスト・図表を多用してわかりやすく解説し、基礎をしっかり固めたい人に最適な参考書です。" },
  { id: "b80", category: "exam",     title: "PT国試 理学療法学 専門問題集 2024", authors: "日本理学療法士協会 監修", publisher: "医学書院", year: 2023, price: "¥4,180", coverUrl: "", keywords: ["国家試験", "PT", "理学療法学", "専門問題", "国試"], summary: "理学療法専門問題に特化した問題集。運動療法・物理療法・評価・疾患別理学療法の全域をカバーし、詳細解説で確実な理解と得点力を身につけられます。" },
];
